---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog posts
  create: documents
  match: "**/*"
  templates:
  - bog-post
- type: directory
  path: content/dictionary
  label: Dictionary entries
  create: documents
  match: "**/*"
  templates:
  - dictionary-entry
- type: directory
  path: content/squad
  label: Squad Members
  create: documents
  match: "**/*"
  templates:
  - squad-member
- type: directory
  path: content/vocabulary
  label: Vocabulary collections
  create: all
  match: "**/*"
  templates:
  - vocabulary
upload_dir: src/assets/images/uploads
public_path: assets/images/uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
